on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: andeo1812/gcc_check_gtest
    steps:
      - uses: actions/checkout@v2 
      - run: make check || exit 0
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    # needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: make build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable-file
        path: build/fib
  test:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    # needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - name: install lcov
        run: apt-get install lcov -y
      - run: make build TEST_OPT=ON
      - run: make run
      - run: make test
      - name: Test coverage
        run: make coverage
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-info
          path: build/report
      - name: launch valgrind tests
        run: valgrind_tests  
      - name: launch valgrind target
        run: valgrind_target  
      - name: launch sanitizer
        run: |
          make build SANITIZE_OPT=ON
          make run
      - name: launch scan-build
        run: |
          apt-get install clang-tools
          make build
          make scan_build

  # fun:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Run a one-line script
  #       run: echo Hello, world!

      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
