on: push

jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   container: leshiy1295/gcc_linters
  #   steps:
  #     - uses: actions/checkout@v2 
  #     - run: ls
  #     - run: pwd
  #     - run: make check
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    # needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: cmake --version
    - run: ls
    - run: pwd
    - run: make build
  # test:
  #   runs-on: ubuntu-latest
  #   container: leshiy1295/gcc_linters
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v2 
  #     - run: make test
  # fun:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Run a one-line script
  #       run: echo Hello, world!

  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.
